### ISSUE TITLE
Review references against other digital editions & fix where appropriate

### ISSUE THREAD

**Issue by DavidHaslam** [timbze/sword-module-text#1]
Some online source editions of the 1646 such as [this one](http://kinseydrivebaptistchurch.com/wp-content/uploads/2017/04/LONDON-BAPTIST.pdf) have corrections and additions to some Scripture references.

We should review each of these and fix where appropriate in the XML file.

**Comment by DavidHaslam** [comment]
Q. How should we record these editorial changes? By **note** elements?

**Comment by timbze** [comment]
> Q. How should we record these editorial changes? By **note** elements?

I like that idea. We can change what we know needs changing and then add a `<note>` element with Editor's note about the change and what the original was.

**Comment by timbze** [comment]
Done
