### ISSUE TITLE
Benjamin Cox's Addendum to the 1646 Confession

### ISSUE THREAD

**Issue by DavidHaslam** [timbze/sword-module-text#2]
It would make sense to include in the same SWORD module the text of [Benjamin Cox's Addendum to the 1646 Confession](https://www.apuritansmind.com/creeds-and-confessions/an-appendix-to-the-baptist-confession-of-faith-by-benjamin-cox/).

**Comment by DavidHaslam** [comment]
I have copied the **Addendum** to an RTF file and edited it to fix various issues in references, punctuation and a few US spellings.

- Some references used the letter `l` instead of digit `1` and vice versa.
- Consecutive verse sequences are changed to a verse range.

**Comment by DavidHaslam** [comment]
The Zip file contains the edited RTF file. 
[An Appendix to the Baptist Confession of Faith - by Benjamin Cox (1646).zip](https://github.com/timbze/sword-module-text/files/4730828/An.Appendix.to.the.Baptist.Confession.of.Faith.-.by.Benjamin.Cox.1646.zip)


This could be used as the basis to make an OSIS XML file with **reference** elements.

**Comment by timbze** [comment]
Added in fb46716b
