### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by DavidHaslam** [timbze/sword-module-text#3]
Rather than simply "sword-module-text", a name that includes **London Baptist Confession 1646 Edition** would make the repository easier to find.

Also, please add a suitable description.

**Comment by timbze** [comment]
I made the repository with generic name so that I could use it for more modules in the future. But maybe it would be better to create new repos for new modules, not sure. I'm leaning toward leaving like this for now. I updated base README and also added README in LBC1646 folder with the name.

**Comment by DavidHaslam** [comment]
I would recommend having a separate repository for each module development project.

**Comment by DavidHaslam** [comment]
**Reminder**: Please add a suitable repository _description_. @timbze

**Comment by timbze** [comment]
Done
