### ISSUE TITLE
Update README and lbc1646.conf to include Benjamin Cox Appendix

### ISSUE THREAD

**Issue by DavidHaslam** [timbze/sword-module-text#5]
Neither the **README.md** file nor the **lbc1646.conf** file in the latest test build mention the inclusion of the **Benjamin Cox Appendix**.

This should be documented in both and the **TextSource** should be extended to mention where the text for the Appendix was obtained from.

Also expand the **Description** and the **About** in the .conf file, and change the **SwordVersionDate** accordingly.

**Comment by DavidHaslam** [comment]
Updated **lbc1646.conf** sent. See also...

[mods.d.zip](https://github.com/timbze/first-london-baptist-confession-1646/files/4798987/mods.d.zip)

**Comment by timbze** [comment]
Done
