### ISSUE TITLE
Top level structure improvement 

### ISSUE THREAD

**Issue by DavidHaslam** [timbze/sword-module-text#6]
IMHO, it would be a useful improvement to insert into the XML structure two top level **div** elements within the **osisText** and make all the existing **div** elements one level lower.

```
	<div type="majorSection" osisID="Confession">
		...
	</div>
	<div type="majorSection" osisID="Appendix_Benjamin Cox">
		...
	</div>
```
This would better reflect the reality that the module contains two source text documents.

This would also aid module navigation in front-ends.

Once this is done, the **osisID** for the Cox introduction could be shortened to `"Appx_Introduction"`.

**Comment by timbze** [comment]
I think that's a good idea. Done here b1b46655

I changed osisID of appendix section to simply Appendix, because And Bible shows the full osisID / chapter osisID for each chapter, so it doesn't look as good. Check out the latest release and let me know if you have any more suggestions.

**Comment by DavidHaslam** [comment]
Any reason why the two **Introduction**s are not a separate level 2 **div** element?

i.e. Just like the **Conclusion** to the **Confession** is already.

IMHO, this would be a better structure.
